### ISSUE TITLE
Setting up payments: Update the payment gateway list

### ISSUE THREAD

**Issue by joshmiller83** [drupalcommerce/commerce-docs#100]
http://docs.drupalcommerce.org/v2/payments/available-payment-gateways.html

This list is quite out of date. Recommend we update it with the following (and maybe link this doc?):

https://docs.google.com/spreadsheets/d/18D9RF6DUoLN1zeeV2aGRW_-QmpHA7eNP56ES8djBRRk/edit#gid=1454227332

**Comment by bojanz** [comment]
Updated Google doc link: https://docs.google.com/spreadsheets/d/1efOOTDFqweCkAnPkIElEbx4yavXoVZjVlJF1fIbtrj8/edit#gid=1454227332

We shouldn't link to a Google Doc, we should transfer the information.

We also need to make a distinction between CG-maintained gateways (Braintree, Stripe, Authorize.net, PayPal, Paymill, Square, Vantiv) and the others.

**Comment by joshmiller83** [comment]
#125
