### ISSUE TITLE
Setting up payments: Complete the Managing Order Payments page

### ISSUE THREAD

**Issue by joshmiller83** [drupalcommerce/commerce-docs#101]
http://docs.drupalcommerce.org/v2/payments/managing-order-payments.html

- [ ] How to locate an order and then find payments that are applied
- [ ] How to void a payment.
- [ ] How to capture a payment.
- [ ] How to refund a payment.
- [ ] How a saved credit card can be managed for your customers (where to find them and how to help a customer update or remove one)

**Comment by mglaman** [comment]
Finished in b8eb030d6199799ec6757d930672fcb4525cfd10 and f5586ace248017c29a9dcbe8f464edcafe9778ad
