### ISSUE TITLE
Product Merchandising: Overview page

### ISSUE THREAD

**Issue by joshmiller83** [drupalcommerce/commerce-docs#102]
We need a page that discusses the merchandising capabilities of Drupal Commerce 2.

- [ ] New, powerful, pricing rules (different from Commerce 1), which are called "Promotions" that handle discounts and coupons
- [ ] Ask Bojan / Matt / Josh / Commerce channel on slack if there is more that could be addressed in this section

**Comment by shabananavas** [comment]
Overview
========

Drupal Commerce Core offers us powerful pricing options that store administrators can leverage to the extent of their store needs. Store admins can create very clever and complex pricing scenarios to entice customers and increase sales.

Promotions and coupons give us the ability to setup and configure pricing rules to meet the store's needs. It can be created quite easily and can be applied to an entire order total or per product.

Creating a Promotion
--------------------

Imagine that your store is currently running a special New Year campaign where you'd like to give customers a 10% discount on orders worth $50 or more. With Commerce Core, it is quite simple.

**Adding a New Promotion**

- We can create a new promotion by going to ``/admin/commerce/promotions`` and clicking the "Add a new promotion" button.

![image](https://user-images.githubusercontent.com/11439056/28079277-4c4d0d2a-6685-11e7-9888-1c5eeeaf7a3a.png)

- Give your promotion a descriptive name, for example, "10% off on $50 or more orders"
  
**Setting the Offer**

  - Let's now decide on the type of offer we'd like to give users. As our goal is to give customers a 10% discount on orders worth $50 or more, let's select the "Percentage off the order total" radio button under ``Offer``.
  - Now enter the percentage you'd like to give the user, example, "10%".

![image](https://user-images.githubusercontent.com/11439056/28079321-7fcfe500-6685-11e7-9ecf-f54d15077ff9.png)

  
**Adding Conditions**

The most interesting part of managing promotions is definitely the conditions section. Currently, Commerce Core gives us the ability to limit applying a promotion based on the following paramters:
- Customer
  - Limit by the customer's billing address
  - Limit by the customer's role
- Order
  - Limit by total price
- Product
  - Limit by the quantity of products the customer purchases
  - Limit by the products that are in the cart
    - You can use the autocomplete to enter a comma separated list of products to apply the promotion to.

Going back to the campaign for our store, we'll go ahead and add an "Order" condition by checking the ``Limit by total price`` checkbox and selecting the ``Greater than`` operator and set the "Amount" to ``50.00``.

![image](https://user-images.githubusercontent.com/11439056/28079344-97513580-6685-11e7-999a-419d2e6427a9.png)


**More Configuration**

We can set further limitations on the promotion, including:
- Dates
  - Set a start and end date for the promotion
- Usage Limits
  - Limit the number of times the promotion can be used
- Compatibility
  - Denote if the promotion can be combined with other promotions

![image](https://user-images.githubusercontent.com/11439056/28079352-a4c92ee8-6685-11e7-82db-25b22c311e28.png)


Now, that we've entered the necessary conditions let's "Save" the promotion. We can test this out by adding a product or a number of products to the cart. Once the order total reaches $50 or more, note, a discount is automatically applied to our order total.

![image](https://user-images.githubusercontent.com/11439056/28079863-8d8b92e6-6687-11e7-869b-f25eecfe276f.png)


Adding a Coupon
---------------
Let's now imagine that we're running a new email campaign that sends customers a coupon that they can use to get 15% off each order over $100. Setting up a coupon based promotion is almost exactly the same as what we did above.

We go through the same steps as creating a promotion, but with one exception. We now use the "Add New Coupon" button.
  - Enter a specific coupon code
  - Mark it as active
  - Set the number of times this coupon can be used

![image](https://user-images.githubusercontent.com/11439056/28079378-c948fd5c-6685-11e7-8970-926dd69103ae.png)


That's it. Now, "Save" the promotion. Let's test this out by adding a few products that amount to an order total of over $100. Notice that a discount is not automatically applied. Instead, in the "Checkout" page, we see a 'Coupon code' textfield. Enter the coupon code in the promotion and hit "Apply coupon". You can now see that the 15% discount has been applied to the entire order.

**Comment by rszrama** [comment]
This is looking great, Shabana! I'll let Bojan / Matt review it for technical accuracy, but I'd like to offer some stylistic / format suggestions for improvement:

1. Use the second person singular pronoun exclusively. The article currently switches between "you / your" and "we / our." For hypothetical scenarios, present them as something the user might want to do and instruct them on how to accomplish it just using "you / your."
2. Make the instruction more direct with fewer conversational remarks / adjectives. (For example, we don't need to say, "That's it" or point out what should be considered "most interesting.")
3. Include a summary either at the top or bottom that identifies key terms with simple definitions. This will help people who don't want to read through a narrative example. (For example, this page can define promotion, offer, condition, coupon, compatibility, etc.)

I love the screenshots / thorough detail!

**Comment by shabananavas** [comment]
@rszrama Thanks so much for your awesome feedback. I've applied your suggestions and have also applied the changes suggested by @joshmiller83 @mglaman and have posted a PR for it here: https://github.com/drupalcommerce/commerce-docs/pull/111.

**Comment by mglaman** [comment]
This was merged.
