### ISSUE TITLE
Contributing to documentation.

### ISSUE THREAD

**Issue by joshmiller83** [drupalcommerce/commerce-docs#103]
We need a page created for how to contribute to Drupal Commerce documentation. 

We want it to look and read like the [contributing page in Getting Started](http://docs.drupalcommerce.org/v2/getting-started/contributing/index.html), but for the documentation side of things.

**Comment by saurabh-vijayvargiya** [comment]
@joshmiller83 P.R. created for this issue -> https://github.com/drupalcommerce/commerce-docs/pull/118

Please review.
