### ISSUE TITLE
Review the Code Recipes

### ISSUE THREAD

**Issue by joshmiller83** [drupalcommerce/commerce-docs#110]
Dimitris has come up with a scoring rubric for Drupal Commerce Code Recipes:

1. Introductory information e.g. what is a product variation type? When to create different variation types and when to use the same? It could include a link to more complete documentation.
2. When to use the snippet e.g. context, situation etc.
3. Where to use the snippet e.g. in a hook?
4. What you need to know if you are coming from Commece 1 e.g. differences in concept or usage etc.
5. What you need to know if you are coming from Drupal 7 e.g. differences in concept or usage etc.
6. Add use statements to the top of the code blocks, most developers would be doing copy/paste and this style improves readability.

On point 6, in all snippets where applicable, correct this:

```
$profile = \Drupal\profile\Entity\Profile::create([
  ‘‘type' => 'customer',
  'uid' => 1,
]);
```

To this:

```
use \Drupal\profile\Entity\Profile;

/**
  * Comments etc.
  */

$profile = Profile::create([
 ‘ type’ => ‘customer’,
  ‘uid’ => 1,
]);
```

**Comment by krystalcode** [comment]
To add to this, there are sites using tabs to provide different options e.g. http://symfony.com/doc/current/routing.html

When a developer comes across a snippet for, let's say, creating a store type, they may wonder "Where do I put this snippet?". And there may be different ways of doing that e.g. defining the types in a YAML file, or programmatically in a hook etc. We could use tabs to provide a more comprehensive list of how to do something.

We need to check if [Sphinx](http://www.sphinx-doc.org/en/stable/) supports tabs though.

**Comment by nandwabee** [comment]
@krystalcode https://github.com/djungelorm/sphinx-tabs

**Comment by nandwabee** [comment]
In line with this I am submitting a PR that shows the general direction that we want to take the 'recipes' section.

**Comment by joshmiller83** [comment]
See #116
