### ISSUE TITLE
Add tabs to the code examples

### ISSUE THREAD

**Issue by nandwabee** [drupalcommerce/commerce-docs#113]
For the code recipes section it might/will be helpful to provide a different experience to different users.

Code examples which might also need to demonstrate Drupal/Commerce best practises (additional detail) vs the 'Quickstart' examples which are there for easy consumption.

This [plugin](https://github.com/djungelorm/sphinx-tabs) provides a good foundation for getting this done.

**Comment by mglaman** [comment]
@nandwabee this was merged.
