### ISSUE TITLE
Revise the outline

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/commerce-docs#132]
I am proposing we take on a stronger outline and structure that identifies our reader personas: User and Developer. The *User* is someone who is going to be interacting with Drupal Commerce, primarily to service a store. The *Developer* is someone implementing Drupal Commerce.

A rough outline via bullets to match outline notes below:

* User guide
  * Key features
  * Setting up your store
    * Importing currencies
    * Creating, editing a store
    * Changing the default store
  * Products
    * Introduction / Before you begin
    * Configuring product attributes
    * Manage product structure
    * Creating a product
    * Editing a product
    * Delete a product
  * Orders
    * Create an order
    * View orders
    * Manage an order
       * Order workflows (overview of default, available workflows)
       * Processing an order
         * With validation
    * Customer receipt emails
  * Payments
    * Capturing an order's payment
    * Voiding an order's authorization
    * Capturing an order's authorization
    * Refunding an order's payment
  * Promotions
    * Create a promotion
    * Using coupons with promotions
    * Managing promotions
  * Taxes
    * European VAT
    * Swiss VAT
    * Canadian GST
    * US Sales tax (push for Avalara)
    * Custom tax rules
  * Checkout
    * Configuring checkout
    * Allowing guest checkout
    * Allow registration at checkout
  * Shipping
    * Introduction (explain it is not part of core)
    * Enable shipping for products
    * Installing and configuring shipping methods
    * Managing shipments
* Developer guide
  * Contributing
     * Setup local environment
  * Installation and updating
    * Using composer
    * Installation
    * Updating
  * Core
    * Conditions
    * HTML emails using Swiftmailer
  * Cart
    * Customizing the add to cart form (specifically the quantity.)
    * Customizing the cart form
  * Payments
    * Gateways and providers
    * Installing and configuring a payment gateway
    * Overriding payment gateway configuration
    * Creating a payment gateway
    * On-site payments
    * Off-site, using iframe
    * Off-site, using redirect
    * Handling an IPN
  * Stores
    * Resolving the current store
  * Orders
    * The order refresh and processing flow
    *  Resolving an order type
  * Checkout
    * Resolving a checkout flow plugin
  * Catalogs
     * Building a catalog using Search API
  * Promotions
     * Providing an offer type
     * Adding a condition (linked to ../Core/Conditions)
  * Shipping
     * Creating a shipping method
  * Adapting from 1.x
    * Understanding Drupal 8 (CM, DI, etc.)
    * The updated product information structure
    * Taxes and VAT (link to the user guide, explain deprecation of contrib.)
    * Shipping (link to the user and developer guide. explain deprecation of contrib)
    * Discounts and coupons (link to the user and developer guide. explain deprecation of contrib)
    * Price calculation
    * Commerce without Rules

# User guide

This section will act as an end-users guide. This is what evaluators and shop managers will read to understand how to use Drupal Commerce. This is where digital agencies can send customers and help build documentation for Drupal Commerce implementation.

## Key Features

Explain some high-level features and link to relevant documentation. This includes multiple stores and currencies for international e-commerce, etc.

## Setting up your store

Covers setting up an initial store.

### Covers importing currencies.

Self explanatory

###  Creating, editing a store

Self explanatory

### Changing the default store

what that means, etc

###  Introduction / Before you begin

Describes product architecture at a high level for the end user -> Products have variations. Variations are made up of different attributes. Before you begin: attributes first.

### Configuring product attributes

* Creating an attribute
* Providing values

### Manage product structure

* Mention there is a "default" which can be used.
* Create a variation type, attach attributes
* Create a product type.

### Delete a product

# Developer guide

This section will be for those implementing Drupal Commerce. It allows us to explain dependencies and how they are used. It will show different integration options. 

The Developer guide will be primarily for audiences who may have a WooCommerce background, for example. It is assumed for anyone who is using Drupal Commerce for the first time.

We will include a *Adapting from 1.x* section. This is a section that essentially highlights how developer implementations in 1.x would be done in 2.x

**Comment by joshmiller83** [comment]
"adapting from 1.x" Migration guide ideas/topics (aka: things that have tripped up D7 people):

- Dependency Injection, wtf?
- Configuration Management and Drupal Commerce.
- Working with Taxes 
- Working with Shipping
- Where did discounts and coupons go? (Hint: Promotions)
- How to do price calculation in Commerce 2 (or: Where did rules go?)
- The Add to Cart Form is built using a form mode
- Modifying the Billing address in checkout (for example, Stripe includes billing address in the credit card form for some reason)

**Comment by mglaman** [comment]
*Where did the nodes go?*: Agree, explaining that we now control all of the structure, including attributes over taxonomy or List (text) fields.

*Dependency Injection, wtf?*: I'd rather make a "Crash course to D8" page which links to important Drupal.org documentation pages and resources. And books, albeit I obviously have a self-interest there.

*Configuration Management and Drupal Commerce.*: We have overriding payment config. Not sure we should cover this is depth. If anything it'd go into the Developer guide and explain developers should take advantage of core's CM system

*Working with Taxes (Hint: Stores are important to the nexus question)*: Covered in user guide. I think this one is straight forward enough we do not need a landing page. Although.. maybe. Because now all those various VAT contrib are part of core. 

*Working with Shipping (What is a package?)* covered in user guide. Developer guide will explain new types. Maybe we can make a page which just links here to explain Shipping in 2.x is a combination of all shipping, shipment, fulfillment modules.

*Where did discounts and coupons go? (Hint: Promotions)*: Same as above. Explain how coupon is part of core, etc.

*How to do price calculation in Commerce 2 (or: Where did rules go?)*: We'll need a whole pricing section in the developer guide (price resolving, attaching adjustments, overriding price in order refresh.) We can point users here and explain when to do what, based on 1.x expectations.

*The Add to Cart Form is built using a form mode* this is part of the developer guide. I think it'd be fine there.

*Modifying the Billing address in checkout* not sure about this one. It'd be really use case specific. I had to do this with Square, for example. Maybe it can go under the section about developing a payment gateway as a "gotcha"

Sections to add:

* Developer guide
  * Payments
    * Creating a payment gateway
    * On-site payments
    * Off-site, using iframe
    * Off-site, using redirect
    * Handling an IPN
  * Adapting from 1.x
    * Understanding Drupal 8 (CM, DI, etc.)
    * The updated product information structure
    * Taxes and VAT (link to the user guide, explain deprecation of contrib.)
    * Shipping (link to the user and developer guide. explain deprecation of contrib)
    * Discounts and coupons (link to the user and developer guide. explain deprecation of contrib)
    * Price calculation


@joshmiller83 how does that above summary sound? If you think I captured your (much appreciated) insight appropriately I'll update the summary

**Comment by joshmiller83** [comment]
Love it! I mentioned the "add to cart" form config is a "form mode" because it tripped up 4 out of 4 D7 commerce professionals last week (including me).

**Comment by mglaman** [comment]
Yeah we'll need a section for customizing the cart features. I added

  * Cart
    * Customizing the add to cart form
    * Customizing the cart form

above. I think I forgot that in outline.

**Comment by wizonesolutions** [comment]
Under adapting from 1.x in the Developer Guide — more about what to do re. Rules sorta not being a thing would be good. Like, I have a bunch of Rules that fire when different Commerce-related stuff happens. I'm guessing the answer is "write code," but something confirming that would be good.

**Comment by mglaman** [comment]
This is in place. I ran the following script to make sure none of the paths in the sitemap returned 404. Came back clean.

```
<?php

$file = 'https://docs.drupalcommerce.org/sitemap';
$domain_to_check = 'https://pr-137-faneb7i-boljpk23hsit6.eu.platform.sh';

$xml = simplexml_load_string(file_get_contents($file));

$paths = [];
foreach ($xml->url as $object) {
  $paths[] = str_replace('https://docs.drupalcommerce.org', '', (string) $object->loc);
}

foreach ($paths as $path_to_check) {
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $domain_to_check.$path_to_check);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_HEADER, 1);
  $output = curl_exec($ch);
  $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
  $header = explode(PHP_EOL, substr($output, 0, $header_size));
  curl_close($ch);

  $status_header = trim($header[0]);
  if ($status_header != 'HTTP/1.1 200 OK' && $status_header != 'HTTP/1.1 302 Found') {
    print_r($header);
    print sprintf('Error with path: %s', $path_to_check) . PHP_EOL;
    break;
  }
}

```

**Comment by mglaman** [comment]
Need to do:

- [ ] s/Configuring/Configure
- [ ] s/What is resolving/Understanding Resolvers
