### ISSUE TITLE
404 on Developer Guide, Products, Product-information-structure

### ISSUE THREAD

**Issue by wizonesolutions** [drupalcommerce/commerce-docs#161]
https://docs.drupalcommerce.org/commerce2/developer-guide/products/product-information-structure

**Comment by mglaman** [comment]
This is due to a missing docs.md file there :/

**Comment by krcha** [comment]
Page created, text pending

**Comment by lisastreeter** [comment]
This page has been moved to: https://docs.drupalcommerce.org/commerce2/developer-guide/products/overview/product-information-structure
Fixed with a new invisible page, with redirect, PR #286: https://github.com/drupalcommerce/commerce-docs/pull/286
