### ISSUE TITLE
Fix the 'Installing' section

### ISSUE THREAD

**Issue by gifthorse** [drupalcommerce/commerce-docs#178]
https://docs.drupalcommerce.org/commerce2/developer-guide/install-update/installation
Now it talks about Drupal 7 due to [this commit](https://github.com/drupalcommerce/commerce-docs/commit/a0ecf62da006bb4730df5d05ac36516300f7d8b5) which moved correct information to some other file.

**Comment by mglaman** [comment]
Thanks, @krcha ^
