### ISSUE TITLE
Consider moving "Getting Started" into its own section above User/Developer Guides

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/commerce-docs#198]
One bit of feedback was that "Getting Started" was hard to find. You had to click "Developer Guide". This might not always been apparent to a user.

One suggestion was to move it into its own top level section. So our tree would be

Commerce 2.x
* Getting Started
* User Guide
* Developer Guide

That way it aligns with comments in #196 to guide users into the specific guides.

**Comment by calbasi** [comment]
I think it is a good idea :-)

**Comment by krcha** [comment]
Thank you, moved!
