### ISSUE TITLE
Documentation Fixes - Page Ordering

### ISSUE THREAD

**Issue by thejacer87** [drupalcommerce/commerce-docs#23]
Firstly there are 2 pages called getting started. One is top level the other in Contributing > Getting Started

Also I think the order should be Installing > Getting Started > Contributing > .... Seems weird to be told how to contribute before how to install.

**Comment by joshmiller83** [comment]
@bojanz / @mglaman .... how do you guys feel about re-ordering the pages?

Current order:

![screenshot1](https://cloud.githubusercontent.com/assets/1440242/15864057/7f183422-2ca3-11e6-83fc-9328ca5c3bd6.png)

My proposed change based on @thejacer87's review:

![screenshot2](https://cloud.githubusercontent.com/assets/1440242/15864119/bda6476a-2ca3-11e6-88ce-45382cdbf435.png)

**Comment by joshmiller83** [comment]
Created PR #24 ... merge if either of you likes this change.

**Comment by joshmiller83** [comment]
![bojanz chat feedback](https://cloud.githubusercontent.com/assets/1440242/15864727/3b694e20-2ca6-11e6-8559-59ada58b2202.png)

Here's a compromise based on @bojanz's feedback (also, updated the PR with this change)

![visual update](https://cloud.githubusercontent.com/assets/1440242/15864711/2a5aed46-2ca6-11e6-9eb4-aad006572b80.png)

**Comment by joshmiller83** [comment]
A few more rounds of back and forth and Bojan finally approves. Merging pull request shortly. Thanks @thejacer87 for the feedback!
