### ISSUE TITLE
Change the Entity Relationship Graph

### ISSUE THREAD

**Issue by joshmiller83** [drupalcommerce/commerce-docs#26]
![image](https://cloud.githubusercontent.com/assets/1440242/15868915/d7e8d994-2cb7-11e6-8ae2-a1ac58147cca.png)

- [x] Change the names to Product Attribute, Product Attribute Value (It sounds more clear, plus it's consistent with product variation (VS just variation))
- [x] Remove `* not fieldable` from Attribute. Attributes are config entities and can be extended using the third party settings API
- [x] Add examples on top of each box: `Color -> Red -> Red DrupalCon T-shirt -> DrupalCon T-shirt`
- [x] Add `Label` & `Weight` to Attribute values 

Work to be pushed to #19

**Comment by joshmiller83** [comment]
![image](https://cloud.githubusercontent.com/assets/1440242/15869235/7fb9141c-2cb9-11e6-901e-accb87e88999.png)

**Comment by bojanz** [comment]
Thanks, Josh!
