### ISSUE TITLE
Document how to create a custom adjustment type

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/commerce-docs#269]
https://www.drupal.org/project/commerce/issues/3018951

**Comment by cmcintosh** [comment]
:/ Any updates to this or a file i can look at to get an idea on how adjustments work.

**Comment by bojanz** [comment]
https://github.com/drupalcommerce/commerce/blob/8.x-2.x/modules/order/commerce_order.commerce_adjustment_types.yml

**Comment by lisastreeter** [comment]
This topic is covered in this Pricing documentation PR: https://github.com/drupalcommerce/commerce-docs/pull/382
