### ISSUE TITLE
Rewrite the attributes to be more concrete with a real example

### ISSUE THREAD

**Issue by joshmiller83** [drupalcommerce/commerce-docs#27]
- [x] Remove or rework the intro to describe a "normal" use case
- [x] Remove or rework the `fieldable entity` section to reduce wordiness and increase clarity
- [x] Reword phrases like "Often this is a very obvious designation falling into the category of a differentiation" to be more basic, 4th grade english

Example intro by Bojan:

> Imagine you need to sell a DrupalCon T-Shirt. This T-Shirt comes in different sizes and colors. Each combination of size and color has its own SKU, used to track the remaining amount of each kind of shirt

Example of furthering the analogy while describing the entity relationships by Bojan:

> Color and Size are product attributes. Blue and small are product attribute values, belonging to the mentioned attributes. The combination of attribute values (with a SKU and a price) is called a product variation. These variations are grouped inside a product.

The work will be reflected in #19

**Comment by bojanz** [comment]
We've done this. Thanks for the many iterations, Josh
