### ISSUE TITLE
Document that gateways that statically set the SDK API key in __construct() also need to do it in __wakeup

### ISSUE THREAD

**Issue by bojanz** [drupalcommerce/commerce-docs#282]
See https://www.drupal.org/project/commerce_stripe/issues/3030159 and https://www.drupal.org/project/commerce/issues/3027924

The gateway object gets serialized in form cache, so when it's unserialized __construct() doesn't run to set the API key. Hence the need to implement __wakeup().

**Comment by lisastreeter** [comment]
Documentation added in PR #298
