### ISSUE TITLE
Document how to safely replace checkout panes

### ISSUE THREAD

**Issue by bojanz** [drupalcommerce/commerce-docs#285]
Moving from drupal.org: https://www.drupal.org/project/commerce/issues/2866429#comment-12021257

Current code docs on the PaymentInformation pane annotation:
```
 * Provides the payment information pane.
 *
 * Disabling this pane will automatically disable the payment process pane,
 * since they are always used together. Developers subclassing this pane
 * should use hook_commerce_checkout_pane_info_alter(array &$panes) to
 * point $panes['payment_information']['class'] to the new child class.
```
Additional details proposed in https://www.drupal.org/project/commerce/issues/3011088

**Comment by lisastreeter** [comment]
New page creating for "replacing checkout panes" in PR: https://github.com/drupalcommerce/commerce-docs/pull/348
