### ISSUE TITLE
Document formatting numbers and prices

### ISSUE THREAD

**Issue by bojanz** [drupalcommerce/commerce-docs#290]
As far as I can see we have no docs covering usage of commerce_price.number_formatter and commerce_price.currency_formatter. Would be great to have.

We can also document the twig filter ("order.getTotalPrice|commerce_price_format") while we're at it.

**Comment by lisastreeter** [comment]
This topic is covered in this Pricing documentation PR: https://github.com/drupalcommerce/commerce-docs/pull/382
