### ISSUE TITLE
Checkout pane example should demonstrate persisting data

### ISSUE THREAD

**Issue by bojanz** [drupalcommerce/commerce-docs#313]
https://docs.drupalcommerce.org/commerce2/developer-guide/checkout/create-custom-checkout-pane only shows how to display a message but developers frequently need to ask for some input and store it somewhere, so we should demonstrate that (using $order->setData() for example)

**Comment by jamie-tillman** [comment]
I think it would also be helpful to identify how to actually show the pane on checkout, rather than AFTER checkout, which is what the example appears to do.  Very confusing.

**Comment by lisastreeter** [comment]
Fixed in https://github.com/drupalcommerce/commerce-docs/pull/346
