### ISSUE TITLE
"View store" permission is required to create a product

### ISSUE THREAD

**Issue by morbus** [drupalcommerce/commerce-docs#324]
See also code-based https://www.drupal.org/project/commerce/issues/3067537.

When one or more stores are available, the following fails:

```
public function testCreateProduct() {
  $this->drupalLogin($this->createUser([
    "create default commerce_product",
  ]));

  $this->drupalGet("product/add/default");
  $this->assertSession()->pageTextNotContains("Products can't be created until a store has been added.");
}
```

Adding the "view commerce_store" permission causes the test to pass.

**Comment by lisastreeter** [comment]
Thanks! Good catch. I've added a note about this to the Products access control page: https://docs.drupalcommerce.org/commerce2/developer-guide/products/product-management/access-control
