### ISSUE TITLE
Request to listing our Payment Gateway called PayDirect FPX

### ISSUE THREAD

**Issue by Shahrul95** [drupalcommerce/commerce-docs#336]
Hi, I'm developer from PayDirect FPX. We're developing a payment gateway system that enable online payment using credit or debit cards (Visa and Mastercard only) and online banking (for Malaysian banks only). Currently PayDirect FPX is only available for businesses that reside in Malaysia. Plus, we already have a few of our clients who currently using Drupal as one of their E-Commerce system. 

We would like to request from your side to add a list from your Payment Gateway List (https://docs.drupalcommerce.org/commerce2/developer-guide/payments/available-gateways) with our PayDirect FPX system. You can review our system at https://www.paydirect.my/. Feel free to email us at support@paydirect.my for any question. 

Best regards,
Shahrul
shahrul@paydirect.my

**Comment by bojanz** [comment]
Sure! Please give us the link to the drupal.org page for your module.

**Comment by Shahrul95** [comment]
Hi, Can you help me on how to upload my module into Drupal websites? You
can download our Drupal module on our websites (
https://www.paydirectfpx.com/plugin/drupal/paydirectfpx-8.x-1.0.tar.gz)

Thanks and Regards

**Comment by Shahrul95** [comment]
Hi,

Sorry for the late reply. I have upload my module to Drupal.org (
https://www.drupal.org/project/paydirectfpx) including with composer.json
file. You may take a look. Hopefully we can work together soon.

Thanks and regards

*Shahrul Izwan*
*System Developer | Projects *
Mob: +60173649224

[image: image.png] <https://paydirect.my/>
*Pay Direct Technology Sdn Bhd*
10-3, 3rd Floor, Jalan PJU 5/9,
Dataran Sunway, Kota Damansara,
Petaling Jaya, 47810 Selangor, Malaysia
Office No: +603-61489545

**Comment by lisastreeter** [comment]
Hi Shahrul,

Thank you for your contribution. I've added your gateway to our list.

**Comment by mitszu1998** [comment]
Hi. Can you remove this post? Because I accidentally include my personal phone number in this thread and it displaying in Google search. Thank you for your consideration.

**Comment by mitszu1998** [comment]
> Hi Shahrul,
> 
> Thank you for your contribution. I've added your gateway to our list.

Hi. Can you remove this post? Because I accidentally include my personal phone number in this thread and it displaying in Google search. Thank you for your consideration.
