### ISSUE TITLE
Where are Product Attributes?

### ISSUE THREAD

**Issue by msypes** [drupalcommerce/commerce-docs#343]
I'm following the User Guide and got to the part about **"Product attributes,"** but no such thing appears on my `/admin/commerce/config` page.
I have instead a **Product variation types**, but from what I'm reading this does not seem to be a simple rename of the same thing.
I've enabled the majority of Commerce's modules, and it doesn't seem I'm missing anything that would obviously create that entity type. Is there something I'm potentially missing, or are the docs outdated? Either way, I'd like to be pointed in the right direction to continue the learning process for setting things up.

**Comment by bojanz** [comment]
In the main menu, one level above, at /admin/commerce

**Comment by msypes** [comment]
Thanks. Boy, do I feel stupid.
