### ISSUE TITLE
Dead link in user guide

### ISSUE THREAD

**Issue by jacobembree** [drupalcommerce/commerce-docs#366]
https://docs.drupalcommerce.org/commerce1/user-guide has a dead link to https://docs.drupalcommerce.org/user-guide/installing-drupal-commerce labelled "Installing Drupal Commerce" in the first paragraph.

**Comment by lisastreeter** [comment]
Thanks! Fixed in this PR: https://github.com/drupalcommerce/commerce-docs/pull/394/files
