### ISSUE TITLE
Typo on Create Payment Gateway Getting started Commerce 2.x Documentation page

### ISSUE THREAD

**Issue by ylynfatt** [drupalcommerce/commerce-docs#376]
There is a small typo in the Commerce 2.x documentation. On the [Create Payment Gateway Getting started](https://docs.drupalcommerce.org/commerce2/developer-guide/payments/create-payment-gateway/getting-started) page, in the section [The buildConfigurationForm() method](https://docs.drupalcommerce.org/commerce2/developer-guide/payments/create-payment-gateway/getting-started#the-buildconfigurationform-method), _configuration_ is spelt incorrectly in the line "To display the fields in the plugin **congiguration** form".

**Comment by lisastreeter** [comment]
Thanks. The PR has been merged.
