### ISSUE TITLE
Rabo omnikassa payment provider available for listing

### ISSUE THREAD

**Issue by joshahubbers** [drupalcommerce/commerce-docs#418]
On the page https://docs.drupalcommerce.org/commerce2/developer-guide/payments/available-gateways are a lot of payment gateways listed. I created one too:

https://www.drupal.org/project/commerce_omnikassa

It is lacking tests because I cannot get my functional js testing environment running yet. But they will be added in the future.

**Comment by joshahubbers** [comment]
Because of the lack of tests, I will not release a stable release yet.

**Comment by lisastreeter** [comment]
Thanks! I've added it to the list. Please let me know if any of the information isn't accurate.
