### ISSUE TITLE
Commerce supports Swiftmailer. How?

### ISSUE THREAD

**Issue by phil-warner** [drupalcommerce/commerce-docs#424]
A handful of bullet-points outlining, within the Commerce documentation, how to configure an HTML email that gets sent when (for example) checkout is complete, seems like a basic requirement, but is conspicuous by its omission.

On the whole, the Commerce documentation is exceptional. It's frustrating when it falls short. 

So, more precisely, how do I create an HTML template within which I can include checkout information, to override the default plain text email?

Thanks

**Comment by lisastreeter** [comment]
Thanks for the suggestion. We do have this documentation page: http://localhost:8081/commerce2/developer-guide/orders/customize-order-receipt-emails

But I agree that this is an aspect of the documentation that could use improvement.

**Comment by phil-warner** [comment]
Hi Lisa

Thank you. I latterly found that page, and figured out the rest. It’s a
great module. Thank you.

With regards, Phil

**Comment by lisastreeter** [comment]
Issue resolved.
