### ISSUE TITLE
SagePay payment gateway available

### ISSUE THREAD

**Issue by dabley** [drupalcommerce/commerce-docs#428]
The list of available payment gateways on https://docs.drupalcommerce.org/commerce2/developer-guide/payments/available-gateways doesnt list SagePay (aka Opayo), although it appears that there is a gateway now available - see https://www.drupal.org/project/commerce_sage (unless I am misunderstanding something).

It is probably also worth keeping this page on wikipedia up to date : https://en.wikipedia.org/wiki/Comparison_of_shopping_cart_software#Payment_gateway_support - as potential users of Drupal Commerce may be put off if it appears that a particular payment gateway isnt available (currently it says that WorldPay isnt supported - which is wrong.)  I will update this.

**Comment by lisastreeter** [comment]
Thanks! I've added SagePay to our available gateways list.

Also, thank you for updating the information on the wikipedia page. That's great!
