### ISSUE TITLE
Commerce 2 checkout merge guest order with existing

### ISSUE THREAD

**Issue by karlshea** [drupalcommerce/commerce-docs#440]
On the configure-checkout page under "Order Information" the docs say that if a user checks out as a guest but uses an email address on an existing account the order will be associated with that account, but that is not the case.

**Comment by lisastreeter** [comment]
Yes, thank you. Good catch. Perhaps this documentation was copy/pasted from a previous version of Commerce. I'll make the update.

**Comment by lisastreeter** [comment]
Merged fix.
