### ISSUE TITLE
Restructure docs, make it more book-like.

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/commerce-docs#47]
I'm proposing a new structure that is more book like, like a cookbook format. This makes it easier to find topics and even redistribute. It also gives us room to notice where we're missing documentation coverage.

*Original*

* Installing
* Updating
* Getting Started
* Dependencies
    * Address
        * Zones
    * Profile
    * State machine
    * Inline Entity Form
* Currency
* Store
* Products
    * Attributes
    * Variations
    * Purchasable Entities
* Orders
    * Order types
    * Order items
    * Order processing
* Contributing
    * Getting started
    * Developing
* Code Recipes

*Proposed*

* Getting Started
    * Introduction to Composer
    * Installing
    * Updating
    * Contributing
        * Developing
* Essential Components
    * Address
    * Profile
    * State machine
    * Inline entity form
    * Currency
* Managing Products
    * Creating attributes
    * Making a product
    * Creating a product type
    * Advanced topics
        * Purchasable attributes
        * Code recipes
* Working with orders
    * Using order types
    * Orders and order items
    * Advanced topics
        * Order processing
        * Code recipes
* Setting up checkout
    * Configuring checkout
    * Advanced topics
        * Creating a checkout pane plugin
        * Creating a checkout flow plugin
* Setting up payments
    * Install a payment gateway
* Using promotions
    * Create promotion, coupon.
* Code recipes
    * Links to each advanced topic for tl;dr users

**Comment by mglaman** [comment]
@bojanz ping on this

**Comment by bojanz** [comment]
Sounds good

**Comment by joshmiller83** [comment]
Sounds awesome!
