### ISSUE TITLE
Complete documentation not found

### ISSUE THREAD

**Issue by BhagiLimbu** [drupalcommerce/commerce-docs#50]
When will be available commerce 2 complete documentation of following topics

1) Catalog and product pages
2) Product merchandising
3) Configuring checkout
4) Payments

Appreciate if you could share release date

**Comment by mglaman** [comment]
We need contributors to help document these items. Or someone to sponsor our time to focus on them.

**Comment by bojanz** [comment]
What Matt said. Documentation is a community effort, pull requests welcome!

**Comment by BhagiLimbu** [comment]
Thank you Matt and Bojan for your quick response. I am new in Drupal and learning now at the moment. I am happy to write documents but I do not have experience. Let me see how fast I can grasp commerce2. Quick question will this be a right place to learn Commerce 2 : https://drupalcommerce.org/commerce-kickstart-2/setup-product-catalog-using-views-taxonomy-and-menu about set up product catalog ?

Thank you.

**Comment by mglaman** [comment]
@BhagiLimbu that documentation is for a distribution built on Commerce 1.x. However a simple View of Products can build a catalog. It's one thing to document

**Comment by BhagiLimbu** [comment]
Thanks Matt!

**Comment by mglaman** [comment]
@BhagiLimbu no problem. As you learn 2.x feel free to open issues here for holes in documentation. It'd be great to document where we need to fill gaps. 

Also, we're also in IRC at #drupal-commerce. You can find myself and @bojanz along with several active contributors who can try to field questions.

if you don't have an IRC client here's some quick web links https://www.irccloud.com/invite?channel=%23drupal-commerce&hostname=irc.freenode.net&port=6697&ssl=1

**Comment by BhagiLimbu** [comment]
I join IRC, will post question if I found issue. Many thanks!

**Comment by mglaman** [comment]
Closing, to clean up queue. We know we need more items :)
