### ISSUE TITLE
Link to repo on Contribute page of DrupalCommerce.org

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/commerce-docs#6]
The page @ https://drupalcommerce.org/contribute should be updated with this repo for documentation and ways to support.

**Comment by joshmiller83** [comment]
Fixed!

![proof of fix](https://cloud.githubusercontent.com/assets/1440242/15864491/5a1d27fc-2ca5-11e6-9ea6-728a076bec87.png)
