### ISSUE TITLE
Remove the address format docs

### ISSUE THREAD

**Issue by bojanz** [drupalcommerce/commerce-docs#60]
The address format UI no longer exists, so half of the address docs page is no longer valid.

**Comment by mglaman** [comment]
@bojanz like this http://pr-61-i7jpkcq-boljpk23hsit6.eu.platform.sh/v2/building-blocks/address/README.html

**Comment by bojanz** [comment]
Yay!
We can rename "Address module" to "Address", and possibly merge Zones into it? Less clicking

**Comment by mglaman** [comment]
@bojanz okay, I merged the two docs, and I removed the "Zones and taxes" section for now.

**Comment by bojanz** [comment]
Merged the PR.
