### ISSUE TITLE
Spec out Drupal 8 API documentation structure

### ISSUE THREAD

**Issue by seanr** [drupalcommerce/commerce-docs#71]
The goal here is to end up with a high-level outline of what the structure of Drupal 8 Commerce API documentation should look like.  That will enable developers to fill in the details in a structured way (as opposed to the mess that is http://www.drupalcontrib.org/api/search/8/commerce?page=1).

- [ ] Commerce classes
  - [ ] Working with products
    - [ ] Loading products
      - [ ] List out methods for loading
    - [ ] Creating products
    - [ ] Updating products
    - [ ] Deleting products
    - [ ] (additional methods)
  - [ ] Working with carts
  - [ ] Working with orders
  - [ ] Working with shipping
- [ ] API changes from Commerce 7 to Commerce 8 (should include all of above with old vs new)

**Comment by joshmiller83** [comment]
See #132
