### ISSUE TITLE
Document setting up order email properly (and how to debug)

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/commerce-docs#91]
* Requirement of Swiftmailer
* Where the Twig file is
* How to setup Mailhog for debugging?

**Comment by bojanz** [comment]
We need a whole page dedicated to overriding the Twig file and customizing the email.

**Comment by bojanz** [comment]
Also raised in https://www.drupal.org/node/2906342

**Comment by mglaman** [comment]
We have

* https://docs.drupalcommerce.org/commerce2/developer-guide/core/html-emails
* https://docs.drupalcommerce.org/commerce2/developer-guide/orders/create-custom-workflow

However we should add informatio about Mailhog in sending HTML emails so people can try and debug easily.

**Comment by mglaman** [comment]
In d5437ac documentation was added for mailhog.
