### ISSUE TITLE
inserting store country united states, using "commerce:create:store" on drupal console is trowing exeption

### ISSUE THREAD

**Issue by noamtahan** [drupalcommerce/commerce-docs#95]
on 
`Enter the store country: United States`
I get 
`[CommerceGuys\Intl\Exception\UnknownCountryException]`

**Comment by bojanz** [comment]
Is there a specific reason why you're opening bug reports in the documentation repository?

Our issue queue is here: https://www.drupal.org/project/issues/commerce

**Comment by noamtahan** [comment]
Sorry. I will open it on  https://www.drupal.org/project/issues/commerce

**Comment by noamtahan** [comment]
Thanks
